Version: 1.6.0

Commands:

  # The list of the ZHorse's commands. You can remove unused commands.
  # Set auto-admin to true to force admin mode for authorized users.
  # The value of cost defines how much will be charged per use.

  admin:
    auto-admin: true
    cost: 0
  claim:
    auto-admin: false
    cost: 0
  free:
    auto-admin: false
    cost: 0
  give:
    auto-admin: false
    cost: 0
  heal:
    auto-admin: false
    cost: 0
  help:
    auto-admin: false
    cost: 0
  here:
    auto-admin: true
    cost: 0
  info:
    auto-admin: false
    cost: 0
  kill:
    auto-admin: false
    cost: 0
  list:
    auto-admin: false
    cost: 0
  lock:
    auto-admin: false
    cost: 0
  rename:
    auto-admin: false
    cost: 0
  protect:
    auto-admin: false
    cost: 0
  reload:
    auto-admin: true
    cost: 0
  settings:
    auto-admin: false
    cost: 0
  share:
    auto-admin: false
    cost: 0
  spawn:
    auto-admin: false
    cost: 0
  tame:
    auto-admin: false
    cost: 0
  tp:
    auto-admin: true
    cost: 0

Groups:

  # The list of permission groups with which ZHorse tries to bind.
  # The value of color is applied to the horse's name.
  # Following formats are available : "&4", <4>, <dark_red>, <DARKRED>.
  # Set color-bypass to allow color tags in horse names.
  # The value of claims-limit defines how much horses a player can claim.
  # The permission is optional if the group is defined in a perms plugin.
  # Membership of the group is simulated for whoever has the permission.
  
  visitor:
    color: <f>
    color-bypass: false
    claims-limit: 0
    permission: zh.group.visitor
  player:
    color: <dark_aqua>
    color-bypass: false
    claims-limit: 5
    permission: zh.what.ever.you.want
  vip:
    color: <3><BOLD>
    color-bypass: false
    claims-limit: 10
    permission: prefix.zh.is.not.required
  admin:
    color: "&c"
    color-bypass: true
    claims-limit: -1
    permission: deleting.this.line.is.fine.too

HorseNames:

  # The default name given to horses if random naming is disabled.
  default-name: DefaultHorseName

  # Set to false to disable random naming.
  give-random-names: true

  # The maximum lenght of a horse's name.
  # If set to 1-36, horse naming is optional.
  # If set to 0, horse naming is forbbiden.
  maximum-length: 36

  # The minimum lenght of a horse's name.
  # If set to more than 0, horse naming is mandatory.
  # If set to 0, horse naming is unrestricted.
  minimum-length: 0

  # The list of words that can't be contained in horse's names.
  banned-names:
  - ExampleName

  # The names that are given randomly if random naming is enabled.
  random-names:
  - Arod
  - Arroch
  - Asfaloth
  - Bill
  - Brego
  - Bumpkin
  - Felar√≥f
  - Firefoot
  - Hasufel
  - Lightfoot
  - Lightning
  - Nahar
  - Pegasus
  - Rochallor
  - Roheryn
  - Shadowfax
  - Sharp-ears
  - Snowmane
  - Strider
  - Stybba
  - Swish-tail
  - Thunderstorm
  - Tornado
  - White-socks
  - Windfola
  - Wise-nose

Languages:

  # The language ZHorse will use for new players.
  # It will be used if a custom locale file is incomplete or corrupted.
  default: EN

  # The list of languages in which players can display ZHorse.
  # You can add other languages if you create a valid locale_XX.yml file.
  available:
  - EN
  - FR
  - NL

Protections:

  # The list of damage types that /zh protect will block.
  # Disable any protection by negating "enabled" or deleting the line.
  
  # Damages caused by players only.

  OWNER_ATTACK:
    enabled: false
  PLAYER_ATTACK:
    enabled: true

  # All kind of damages except those caused by players.

  BLOCK_EXPLOSION:
    enabled: false
  CONTACT:
    enabled: false
  CUSTOM:
    enabled: false
  DRAGON_BREATH:
    enabled: false
  DROWNING:
    enabled: false
  ENTITY_ATTACK:
    enabled: false
  ENTITY_EXPLOSION:
    enabled: false
  FALL:
    enabled: false
  FALLING_BLOCK:
    enabled: false
  FIRE:
    enabled: false
  FIRE_TICK:
    enabled: false
  FLY_INTO_WALL:
    enabled: false
  LAVA:
    enabled: false
  LIGHTNING:
    enabled: false
  MAGIC:
    enabled: false
  MELTING:
    enabled: false
  POISON:
    enabled: false
  PROJECTILE:
    enabled: false
  STARVATION:
    enabled: false
  SUFFOCATION:
    enabled: false
  SUICIDE:
    enabled: false
  THORNS:
    enabled: false
  VOID:
    enabled: false
  WITHER:
    enabled: false

Settings:

  # Set to false to block leashes on dead horses. (tamed only !)
  allow-leash-on-dead-horse: true

  # Set to true to block /zh here on leashed horses.
  block-leashed-teleport: false
  
  # Set to true to block /zh here on mounted horses.
  block-mounted-teleport: false

  # Set to true to make player execute /zh claim on horse tame.
  claim-on-tame: false

  # Set to true to make player execute /zh lock on horse claim.
  lock-on-claim: false

  # Set to true to make player execute /zh protect on horse claim.
  protect-on-claim: false

  # Set to true to make player execute /zh share on horse claim.
  share-on-claim: false

  # Set to true to hide all ZHorse messages in chat.
  mute-console: false

  # Set to true to switch to the teleportation method used in 1.4-.
  # This is only recommended for servers using plugins that are
  # incompatible with the new 1.5+ teleportation method.
  use-old-teleport-method: false

Worlds:

  # The list of worlds that ZHorse can interact with.
  # Set enabled to false to disable ZHorse in a world.
  # Set crossable to false to disable /zh tp and /zh here in a world.

  world:
    enabled: true
    crossable: true
  world_nether:
    enabled: false
    crossable: false
  world_the_end:
    enabled: false
    crossable: false