Version: 1.4.0

Commands:

  # The list of the ZHorse's commands. You can remove unused commands.
  # Set auto-admin to true to force admin mode for authorized users.
  # The value of cost defines how much will be charged per execution.

  claim:
    auto-admin: false
    cost: 0
  free:
    auto-admin: false
    cost: 0
  give:
    auto-admin: false
    cost: 0
  heal:
    auto-admin: false
    cost: 0
  help:
    auto-admin: false
    cost: 0
  here:
    auto-admin: true
    cost: 0
  info:
    auto-admin: false
    cost: 0
  kill:
    auto-admin: false
    cost: 0
  list:
    auto-admin: false
    cost: 0
  lock:
    auto-admin: false
    cost: 0
  rename:
    auto-admin: false
    cost: 0
  protect:
    auto-admin: false
    cost: 0
  reload:
    auto-admin: true
    cost: 0
  settings:
    auto-admin: false
    cost: 0
  share:
    auto-admin: false
    cost: 0
  tame:
    auto-admin: false
    cost: 0
  tp:
    auto-admin: true
    cost: 0

Groups:

  # The list of groups with which ZHorse tries to bind.
  # The value of color is applied before the horse's name.
  # Following formats are available : <4>, ^4, §4, <dark_red>, <darkred>.
  # The value of claims-limit defines how much horses a player can claim.
  # The permission is optional if the group is defined in a perms plugin.
  # Membership of the group is simulated for whoever owns the permission.
  
  default:
    color: <f>
    claims-limit: 0
    permission: zh.group.default
  player:
    color: <dark_aqua>
    claims-limit: 5
    permission: zh.what.ever.you.want
  vip:
    color: <BOLD>
    claims-limit: 10
    permission: prefix.zh.is.not.required
  admin:
    color: ^c
    claims-limit: -1
    permission: deleting.this.line.is.fine.too

HorseNames:

  # The default name given to horses if random naming is disabled.
  default-name: DefaultHorseName

  # Set to false to disable random naming.
  give-random-names: true

  # The maximum lenght of a horse's name.
  # If set to more than 0, length of horse's name is limited.
  # If set to 0, horse naming is forbbiden.
  # If set to -1, horse naming is optional.
  maximum-length: 30

  # The minimum lenght of a horse's name.
  # If set to more than 0, horse naming is mandatory.
  # If set to 0, horse naming is unrestricted.
  minimum-length: 0

  # The list of words that can't be contained in horse's names.
  banned-names:
  - ExampleName

  # The names that are given randomly if random naming is enabled.
  random-names:
  - Arod
  - Ashufel
  - Grispoil
  - Eclair
  - Lightning
  - Pegase
  - Ponyta
  - Thunderstorm
  - Tonnerre
  - Tornado

Languages:

  # The language ZHorse will use for new players.
  # It will be used if a locale file is incomplete or corrupted.
  default: EN

  # The list of languages in which players can display ZHorse.
  # You can add other languages if you create a valid locale_XX.yml file.
  available:
  - EN
  - FR

Protections:

  # The list of damage types that /zh protect will block.
  # Disable any protection by negating "enabled" or deleting the line.
  
  # Damages caused by players only.

  OWNER_ATTACK:
    enabled: false
  PLAYER_ATTACK:
    enabled: true

  # All kind of damages minus those caused by players.

  BLOCK_EXPLOSION:
    enabled: false
  CONTACT:
    enabled: false
  CUSTOM:
    enabled: false
  DROWNING:
    enabled: false
  ENTITY_ATTACK:
    enabled: false
  ENTITY_EXPLOSION:
    enabled: false
  FALL:
    enabled: false
  FALLING_BLOCK:
    enabled: false
  FIRE:
    enabled: false
  FIRE_TICK:
    enabled: false
  LAVA:
    enabled: false
  LIGHTNING:
    enabled: false
  MAGIC:
    enabled: false
  MELTING:
    enabled: false
  POISON:
    enabled: false
  PROJECTILE:
    enabled: false
  STARVATION:
    enabled: false
  SUFFOCATION:
    enabled: false
  SUICIDE:
    enabled: false
  THORNS:
    enabled: false
  VOID:
    enabled: false
  WITHER:
    enabled: false

Settings:

  # Set to true to hide all ZHorse messages in player's chat.
  mute-console: false

  # Set to true to make players execute /zh claim when taming a horse.
  claim-on-tame: false

  # Set to true to make players execute /zh lock when claiming a horse.
  lock-on-claim: false

  # Set to true to make players execute /zh protect when claiming a horse.
  protect-on-claim: false

  # Set to true to make players execute /zh share when claiming a horse.
  share-on-claim: false

Worlds:

  # The list of worlds that ZHorse can interact with.
  # Set enabled to false to disable ZHorse in that world.
  # Set crossable to false to disable /zh tp and /zh here in that world.

  world:
    enabled: true
    crossable: true
  world_nether:
    enabled: false
    crossable: false
  world_the_end:
    enabled: false
    crossable: false