Version: ${version}

# Please make sure to visit ZHorse Wiki if you encounter any issue: https://github.com/Zedd7/ZHorse/wiki/Commands
# Commands usage tutorial: https://github.com/Zedd7/ZHorse/wiki/Commands
# Permissions assignation tutorial: https://github.com/Zedd7/ZHorse/wiki/Permissions
# Tips and tricks: https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks

Commands:

  # The list of ZHorse commands. You can remove unused commands.
  # Set auto-admin to true to force admin mode for authorized users.
  # The value of cooldown defines the delay between two executions in seconds.
  # The value of cost defines how much will be charged per use.

  admin:
    auto-admin: true
    cooldown: 0
    cost: 0
  buy:
    auto-admin: false
    cooldown: 0
    cost: 0
  claim:
    auto-admin: false
    cooldown: 0
    cost: 0
  edit:
    auto-admin: false
    cooldown: 0
    cost: 0
  free:
    auto-admin: false
    cooldown: 0
    cost: 0
  friend:
    auto-admin: false
    cooldown: 0
    cost: 0
  give:
    auto-admin: false
    cooldown: 0
    cost: 0
  heal:
    auto-admin: false
    cooldown: 0
    cost: 0
  help:
    auto-admin: false
    cooldown: 0
    cost: 0
  here:
    auto-admin: true
    cooldown: 0
    cost: 0
  info:
    auto-admin: false
    cooldown: 0
    cost: 0
  kill:
    auto-admin: false
    cooldown: 0
    cost: 0
  list:
    auto-admin: false
    cooldown: 0
    cost: 0
  lock:
    auto-admin: false
    cooldown: 0
    cost: 0
  protect:
    auto-admin: false
    cooldown: 0
    cost: 0
  rename:
    auto-admin: false
    cooldown: 0
    cost: 0
  reload:
    auto-admin: true
    cooldown: 0
    cost: 0
  rez:
    auto-admin: false
    cooldown: 0
    cost: 0
  sell:
    auto-admin: false
    cooldown: 0
    cost: 0
  settings:
    auto-admin: false
    cooldown: 0
    cost: 0
  share:
    auto-admin: false
    cooldown: 0
    cost: 0
  spawn:
    auto-admin: false
    cooldown: 0
    cost: 0
  stable:
    auto-admin: true
    cooldown: 0
    cost: 0
  tame:
    auto-admin: false
    cooldown: 0
    cost: 0
  tp:
    auto-admin: true
    cooldown: 0
    cost: 0

Databases:

  # The type of SQL database that ZHorse should use.
  # Available databases types are MySQL, SQLite.
  type: SQLite

  # Configuration section for SQLite. You can remove it if SQLite is disabled.
  sqlite-config:
    # The name of the database file without extension
    filename: zhorse

  # Configuration section for MySQL. You can remove it if MySQL is disabled.
  # The field table-prefix is optional. Use it only in case of shared database.
  mysql-config:
    host: 127.0.0.1
    port: 3306
    user: ZHorse
    password: ''
    database: zhorse
    table-prefix: ''

Groups:

  # The list of permission groups with which ZHorse tries to bind.
  # The value of color is applied to the horse name.
  # Following formats are available : "&4", <4>, <dark_red>, <DARKRED>.
  # Set color-bypass to allow color tags in horse names.
  # The value of claims-limit defines how much horses a player can claim.
  # Assign and define the permission only if the group is not defined in a perms plugin.
  # Membership of the (fake) group is simulated for whoever has the permission.

  visitor:
    color: <f>
    color-bypass: false
    claims-limit: 0
    permission: zh.group.visitor
  player:
    color: <dark_aqua>
    color-bypass: false
    claims-limit: 5
    permission: zh.what.ever.you.want
  vip:
    color: <3><BOLD>
    color-bypass: false
    claims-limit: 10
    permission: prefix.zh.is.not.required
  admin:
    color: "&c"
    color-bypass: true
    claims-limit: -1
    permission: deleting.this.line.is.fine.too

HorseNames:

  # The maximum length of a horse name.
  # If set to 1-36, horse naming is optional.
  # If set to 0, horse naming is forbidden.
  maximum-length: 36

  # The minimum length of a horse name.
  # If set to more than 0, horse naming is mandatory.
  # If set to 0, horse naming is unrestricted.
  minimum-length: 0

  # The default name given to horses if random naming is disabled.
  default-name: DefaultHorseName

  # Set to false to disable random naming.
  give-random-names: true

  # The names that are given randomly if random naming is enabled.
  random-names:
  - Arod
  - Arroch
  - Asfaloth
  - Bill
  - Brego
  - Bumpkin
  - Felar√≥f
  - Firefoot
  - Hasufel
  - Lightfoot
  - Lightning
  - Nahar
  - Pegasus
  - Rochallor
  - Roheryn
  - Shadowfax
  - Sharp-ears
  - Snowmane
  - Strider
  - Stybba
  - Swish-tail
  - Thunderstorm
  - Tornado
  - White-socks
  - Windfola
  - Wise-nose

  # The list of words which cannot be contained in horse names.
  banned-names:
  - ExampleName

Languages:

  # The language ZHorse will use for new players.
  # It will be used if a custom locale file is incomplete or corrupted.
  default: EN

  # The list of languages in which players can display ZHorse.
  # You can add other languages if you create a valid locale_XX.yml file.
  available:
  - CN
  - DE
  - EN
  - ES
  - FR
  - HU
  - NL
  - PL

Protections:

  # The list of damage types that /zh protect will block.
  # Disable any protection by negating "enabled" or deleting the line.

  # Damages caused by players only.

  OWNER_ATTACK:
    enabled: false
  PLAYER_ATTACK:
    enabled: true

  # All kind of damages except those caused by players.

  BLOCK_EXPLOSION:
    enabled: false
  CONTACT:
    enabled: false
  CRAMMING:
    enabled: false
  CUSTOM:
    enabled: false
  DRAGON_BREATH:
    enabled: false
  DROWNING:
    enabled: false
  ENTITY_ATTACK:
    enabled: false
  ENTITY_EXPLOSION:
    enabled: false
  ENTITY_SWEEP_ATTACK:
    enabled: false
  FALL:
    enabled: false
  FALLING_BLOCK:
    enabled: false
  FIRE:
    enabled: false
  FIRE_TICK:
    enabled: false
  FLY_INTO_WALL:
    enabled: false
  HOT_FLOOR:
    enabled: false
  LAVA:
    enabled: false
  LIGHTNING:
    enabled: false
  MAGIC:
    enabled: false
  MELTING:
    enabled: false
  POISON:
    enabled: false
  PROJECTILE:
    enabled: false
  STARVATION:
    enabled: false
  SUFFOCATION:
    enabled: false
  SUICIDE:
    enabled: false
  THORNS:
    enabled: false
  VOID:
    enabled: false
  WITHER:
    enabled: false

Settings:

  # Set to false to block foal riding and claiming.
  allow-foal-riding: true

  # Set to false to block leashes on (tamed adult) undead horses.
  allow-leash-on-undead-horse: true

  # Set to false to block players from taming undead horses.
  allow-taming-of-undead-horse: true

  # Set to true to block teleportation of leashed horses.
  block-leashed-teleport: false

  # Set to true to block teleportation of mounted horses.
  block-mounted-teleport: false

  # Set to true to make player execute /zh claim on horse tame.
  claim-on-tame: false

  # Set to true to make player execute /zh lock on horse claim.
  lock-on-claim: false

  # Set to true to make player execute /zh protect on horse claim.
  protect-on-claim: false

  # Set to true to make player execute /zh share on horse claim.
  share-on-claim: false

  # Prevent /zh here if horse is outside the maximum radius (in blocks).
  # Set to -1 for infinite range.
  here-max-range: -1

  # Prevent /zh stable if horse is outside the maximum radius (in blocks).
  # Set to -1 for infinite range.
  stable-max-range: -1

  # Prevent /zh tp if horse is outside the maximum radius (in blocks).
  # Set to -1 for infinite range.
  tp-max-range: -1

  # Set to false to disable respawn of missing horses.
  # If a horse happens to be missing (possible bug) and its
  # stats and inventory are registered in the database (automatic),
  # a perfect copy of it will be spawned at its last seen location.
  respawn-missing-horse: true

  # Set to false to prevent items from being stored on horse death.
  # It will make them available for looting but they will not be
  # restored in the horse inventory when it gets resurrected.
  restore-inventory: true

  # The number of dead horses kept in the database for each player.
  # Higher values allow players to resurrect more dead horses.
  # Lower values (including 0, to disable) use less space in the database.
  rez-stack-size: 5

  # Set to true to make default stats display mode use unrounded horse stats.
  # Does not affect actual horse stats, only applies to /zh spawn and /zh info.
  use-exact-stats: false

  # Set to false to use vanilla thresholds for horse stats.
  # Does not affect actual horse stats, only applies to /zh spawn and /zh info.
  use-vanilla-stats: true

  # Set to true to switch to the teleportation method used in ZHorse 1.4-.
  # This is only recommended for servers using plugins that are
  # incompatible with the new ZHorse 1.5+ teleportation method.
  # The new method removes horses and respawns them at destination.
  use-old-teleport-method: false
  
  # Set to true to use the location defined by default-stable-location for
  # horses whose stable has not been defined when using /zh stable go or
  # when a player logout and send-to-stable-on-owner-logout is enabled.
  use-default-stable: false
  
  # Set to true to send horses to stable when their owner logout.
  # This only works if a regular or default stable has been defined.
  # Leashing horses and enabling block-leashed-teleport is recommended.
  send-to-stable-on-owner-logout: false

  # The location of the default stable. It is only considered for horses
  # whose own stable has not been defined with /zh stable set.
  default-stable-location:
    world: world
    x: 1
    y: 64
    z: -1

  # Set to false to disable the update checker searching for new releases.
  check-for-update: true

  # Set to true to hide all ZHorse messages in chat.
  mute-console: false

Worlds:

  # The list of worlds that ZHorse can interact with.
  # Set enabled to false to disable ZHorse in a world.
  # Any world not listed here will be disabled.
  # Set crossable to false to disable /zh tp, /zh here and /zh tame in a world.

  world:
    enabled: true
    crossable: true
  world_nether:
    enabled: false
    crossable: false
  world_the_end:
    enabled: false
    crossable: false
